config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, path: 'cms-auth', path_names: { sign_in: 'signin', sign_out: 'signout' }

  devise_for :users,
             path_names: { sign_in: 'signin', sign_up: 'singup', sign_out: 'signout' },
             controllers: { cas_sessions: 'cas_sessions' }
  get 'auth/twitter', as: :twitter_auth
  get 'auth/twitter/callback', to: 'twitter#create'
  delete 'auth/twitter/:id', to: 'twitter#destroy', as: :remove_twitter

  get 'sitemap' => 'site#sitemap', format: :xml

  get 'admin', to: redirect('/admin/dashboard')
  namespace :admin do
    get 'dashboard' => 'dashboard#index'

    get 'digest' => 'dashboard#digest', as: :digest

    resources :posts do
      get 'twitter-alerts', action: :new_twitter_alert
      put 'twitter-alerts', action: :alert_via_twitter
    end
    resources :blog_posts
    resources :authors
    resources :post_sections, path: 'sections'
    resources :events
    resources :central_banks, path: 'central-banks'
    resources :links
    resources :countries
    resources :pages, only: [:index, :edit, :update]
    resources :charts

    resources :sales_managers
    resources :users, only: [:index, :edit, :update] do
      get 'export', action: :export, on: :collection
    end
    resources :email_alerts, path: 'manual-email-alerts', only: [:new, :index, :show, :destroy] do
      get 'common-settings', action: 'common_settings'
      put 'common-settings', action: 'update_common_settings'

      get 'custom-texts', action: 'custom_texts'
      put 'custom-texts', action: 'update_custom_texts'
    end

    resources :email_alert_schedules, path: 'email-alerts-schedule', only: [:index, :new, :show, :create, :update, :destroy, :edit]
    resources :pdf_email_alerts, path: 'pdf-alerts', only: [:index, :new, :create] do
      member do
        get :preview
        put 'send', action: 'send_pdf'
      end
    end


    resources :site_settings, path: 'settings', only: [:index, :update]
  end

  resources :blog_posts, only: [:index, :show], path: 'blog'
  resources :posts, only: [:index, :show] do
    collection do
      get 'section/:section_slug', action: :index, as: :section
      get 'country/:country_slug', action: :index, as: :country
    end

    post 'mark-read', action: :mark_read, on: :member
  end

  resources :events, only: :index
  resources :links, only: :index

  resources :central_banks, only: :index, path: 'central-banks'
  resources :authors, only: [:show]
  resources :subscribers, only: [:create]
  resource  :user, only: [:create, :edit, :update] do
    collection do
      post :short_create
      post :invite_request
    end
  end

  get 'search' => 'search#index', as: :search

  get ':slug' => 'pages#show', as: :page

  root to: 'posts#index', is_home_page: true
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :country
  scope :upcoming,  -> { where('date > ?', Time.zone.now).order(:date) }
  scope :in_ticker, -> { where(in_ticker: true) }

  validates :title, :country_id, :date, :time_local, :time_gmt, presence: true
  validates :title, :data_for, length: { maximum: 255 }
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < AdminController
  def index
    @events = Event.paginate(paginate_params)
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      flash[:success] = 'Event was successfully created'

      redirect_to admin_events_path
    else
      flash[:error] = "Can't create a event. Checkout the errors below"
      render 'new'
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update_attributes(event_params)
      flash[:success] = 'Event was successfully updated'

      redirect_to admin_events_path
    else
      flash[:error] = 'Please checkout the event updating errors'
      render 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy if @event.present?

    redirect_to admin_events_path, flash: { success: 'Event was successfully destroyed' }
  end


  protected

  def event_params
    params.require(:event).permit(:title, :data_for, :country_id, :date, :time_local, :time_gmt, :in_ticker)
  end
end

app/controllers/events_controller.rb
class EventsController < FrontController
  def index
    @events = Event.upcoming
  end
end

app/views/admin/events/_form.html.slim
= simple_form_for [:admin, @event], html: { class: 'form form-horizontal' }, wrapper: :horizontal_form do |f|
  .form-body
    = f.input :title
    = f.input :data_for
    = f.association :country
    = f.input :in_ticker, as: :boolean

    hr

    = f.input :date, as: :date
    = f.input :time_local, as: :time
    = f.input :time_gmt, as: :time

  = form_buttons f, cancel_path: admin_events_path

app/views/admin/events/_header_and_breadcrumbs.html.slim
.row
  .col-md-12
    h3.page-title
      i.fa.fa-header.fa-calendar
      '
      ' Events
      small management

    ul.page-breadcrumb.breadcrumb
      li.btn-group
        = link_to new_admin_event_path, class: 'btn btn-primary blue' do
          i class="fa fa-plus"
          span Add new event
      li
        i class="fa fa-home"
        '
        = link_to 'Dashboard', admin_path
      - breadcrumbs.each do |name, path|
        li
          '
          i class="fa fa-angle-right"
          '
          = link_to raw(name), path
.row
  .col-md-12
    = render 'flash_messages'

app/views/admin/events/edit.html.slim
= render 'header_and_breadcrumbs',
  breadcrumbs: { 'Event' => admin_posts_path,
                 "Editing <small>'#{truncate(@event.title, length: 40)}'</small>" => edit_admin_event_path(@event) }
h1.page-title= "Editing  ' #{@event.title} '"
= render 'form'

app/views/admin/events/index.html.slim
= render 'header_and_breadcrumbs', breadcrumbs: {'Events' => admin_events_path }
- if @events.any?
  table.table.table-striped.table-hover.table-events
    thead
      tr
        th Date
        th Title
        th Description
        th.actions Actions
    tbody
      - @events.each do |event|
        - edit_path = edit_admin_event_path(event)
        tr.gradeX
          td = link_to l(event.date, format: :short), edit_path
          td = link_to event.title, edit_path
          td = link_to truncate(event.data_for, length: 60), edit_path

          td.actions
            = link_to edit_path, class: 'btn default btn-xs purple'
              i.fa.fa-edit>
              | Edit
            '
            = link_to admin_event_path(event), class: 'btn default btn-xs', method: :delete, data: {confirm: 'Are you sure?'} do
              i.fa.fa-trash-o>
              | Delete

  .pagination-container.clearfix
    = paginate_list @events
    = paginate_per
- else
  .no-items
    p There are no events

app/views/admin/events/new.html.slim
= render 'header_and_breadcrumbs',
  breadcrumbs: { 'Events' => admin_events_path,
                 'Creating new event' => new_admin_event_path }

h1.page-title New event
= render 'form'