config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, path: 'cms-auth', path_names: { sign_in: 'signin', sign_out: 'signout' }

  devise_for :users,
             path_names: { sign_in: 'signin', sign_up: 'singup', sign_out: 'signout' },
             controllers: { cas_sessions: 'cas_sessions' }
  get 'auth/twitter', as: :twitter_auth
  get 'auth/twitter/callback', to: 'twitter#create'
  delete 'auth/twitter/:id', to: 'twitter#destroy', as: :remove_twitter

  get 'sitemap' => 'site#sitemap', format: :xml

  get 'admin', to: redirect('/admin/dashboard')
  namespace :admin do
    get 'dashboard' => 'dashboard#index'

    get 'digest' => 'dashboard#digest', as: :digest

    resources :posts do
      get 'twitter-alerts', action: :new_twitter_alert
      put 'twitter-alerts', action: :alert_via_twitter
    end
    resources :blog_posts
    resources :authors
    resources :post_sections, path: 'sections'
    resources :events
    resources :central_banks, path: 'central-banks'
    resources :links
    resources :countries
    resources :pages, only: [:index, :edit, :update]
    resources :charts

    resources :sales_managers
    resources :users, only: [:index, :edit, :update] do
      get 'export', action: :export, on: :collection
    end
    resources :email_alerts, path: 'manual-email-alerts', only: [:new, :index, :show, :destroy] do
      get 'common-settings', action: 'common_settings'
      put 'common-settings', action: 'update_common_settings'

      get 'custom-texts', action: 'custom_texts'
      put 'custom-texts', action: 'update_custom_texts'
    end

    resources :email_alert_schedules, path: 'email-alerts-schedule', only: [:index, :new, :show, :create, :update, :destroy, :edit]
    resources :pdf_email_alerts, path: 'pdf-alerts', only: [:index, :new, :create] do
      member do
        get :preview
        put 'send', action: 'send_pdf'
      end
    end


    resources :site_settings, path: 'settings', only: [:index, :update]
  end

  resources :blog_posts, only: [:index, :show], path: 'blog'
  resources :posts, only: [:index, :show] do
    collection do
      get 'section/:section_slug', action: :index, as: :section
      get 'country/:country_slug', action: :index, as: :country
    end

    post 'mark-read', action: :mark_read, on: :member
  end

  resources :events, only: :index
  resources :links, only: :index

  resources :central_banks, only: :index, path: 'central-banks'
  resources :authors, only: [:show]
  resources :subscribers, only: [:create]
  resource  :user, only: [:create, :edit, :update] do
    collection do
      post :short_create
      post :invite_request
    end
  end

  get 'search' => 'search#index', as: :search

  get ':slug' => 'pages#show', as: :page

  root to: 'posts#index', is_home_page: true
end

app/views/admin/_connect_to_twitter_alert.html.slim
.alert.alert-warning.alert-dismissable
  button.close aria-hidden="true" data-dismiss="alert" type="button"
  ' Please connect
  => link_to 'Twitter account', admin_site_settings_path
  ' to be able to tweet

app/views/admin/_flash_messages.html.slim
- class_names_mapping = { success: 'success', error: 'danger', alert: 'warning'}

- flash.each do |type, message|
  - type = type.to_sym
  .app-alerts.alert.fade.in class="alert-#{class_names_mapping[type]}"
    button type="button" class="close" data-dismiss="alert" aria-hidden="true"
    == '<strong>Error!</strong> ' if type == :error
    == '<strong>Success!</strong> ' if type == :success

    = message

app/views/admin/_footer.html.slim
.footer
  .footer-inner
    => Date.today.year
    ' &copy;
    = link_to 'MNI Asia Insight', '//'
  .footer-tools
    span.go-top
      i.fa.fa-angle-up

app/views/admin/_header.html.slim
.header.navbar.navbar-fixed-top
  .header-inner
    = link_to admin_path, class: 'navbar-brand' do
      = image_tag 'logo-asia-insight.svg', class: 'img-responsive'

    = link_to 'Control panel', admin_path, class: 'navbar-cp-title'

    ul.nav.navbar-nav.pull-right
      li.dropdown.user
        = link_to destroy_admin_user_session_path do
          i.fa.fa-external-link>
          span.username Log out

    .user-online.pull-right
      ' Editors online:
      strong= @signed_is_users_count


.clear

app/views/admin/_sidebar.html.slim
.page-sidebar-wrapper
  .page-sidebar.navbar-collapse.collapse
    ul.page-sidebar-menu data-auto-scroll="true" data-slide-speed="200"
      li.sidebar-toggler-wrapper
        .sidebar-toggler.hidden-phone

      li.start
        = link_to root_path do
          i.fa.fa-mail-reply
          span.title To website

      li.heading
        h3.uppercase Content
      = active_link_to admin_dashboard_path, wrap_tag: :li do
        i.fa.fa-home
        span.title Dashboard
      = active_link_to admin_events_path, wrap_tag: :li do
        i.fa.fa-calendar
        span.title Events
      = active_link_to admin_authors_path, wrap_tag: :li do
        i.fa.fa-users
        span.title Authors
      = active_link_to admin_posts_path, wrap_tag: :li do
        i.fa.fa-files-o
        span.title Posts
      = active_link_to admin_post_sections_path, wrap_tag: :li do
        i.fa.fa-tags
        span.title Post sections
      = active_link_to admin_blog_posts_path, wrap_tag: :li do
        i.fa.fa-pencil
        span.title Blog Posts
      = active_link_to admin_countries_path, wrap_tag: :li do
        i.fa.fa-globe
        span.title Countries
      = active_link_to admin_charts_path, wrap_tag: :li do
        i.fa.fa-arrows-h
        span.title Economic focus
      = active_link_to admin_central_banks_path, wrap_tag: :li do
        i.fa.fa-dollar
        span.title Central banks
      = active_link_to admin_links_path, wrap_tag: :li do
        i.fa.fa-external-link-square
        span.title Links
      = active_link_to admin_pages_path, wrap_tag: :li do
        i.fa.fa-file-text-o
        span.title Pages

      li.heading
        h3.uppercase Marketing & Sales
      = active_link_to admin_sales_managers_path, wrap_tag: :li do
        i.fa.fa-bullhorn
        span.title Sales managers
      = active_link_to admin_users_path, wrap_tag: :li do
        i.fa.fa-group
        span.title Users
      = active_link_to admin_email_alerts_path, wrap_tag: :li do
        i.fa.fa-envelope
        span.title Manual Email Alerts
      = active_link_to admin_email_alert_schedules_path, wrap_tag: :li do
        i.fa.fa-paper-plane-o
        span.title Automatic Email Alerts
      = active_link_to admin_pdf_email_alerts_path, wrap_tag: :li do
        i.fa.fa-file-pdf-o
        span.title Pdf Email Alerts

      li.heading
        h3.uppercase Configuration
      = active_link_to admin_site_settings_path, wrap_tag: :li do
        i.fa.fa-cogs
        span.title Site settings