config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, path: 'cms-auth', path_names: { sign_in: 'signin', sign_out: 'signout' }

  devise_for :users,
             path_names: { sign_in: 'signin', sign_up: 'singup', sign_out: 'signout' },
             controllers: { cas_sessions: 'cas_sessions' }
  get 'auth/twitter', as: :twitter_auth
  get 'auth/twitter/callback', to: 'twitter#create'
  delete 'auth/twitter/:id', to: 'twitter#destroy', as: :remove_twitter

  get 'sitemap' => 'site#sitemap', format: :xml

  get 'admin', to: redirect('/admin/dashboard')
  namespace :admin do
    get 'dashboard' => 'dashboard#index'

    get 'digest' => 'dashboard#digest', as: :digest

    resources :posts do
      get 'twitter-alerts', action: :new_twitter_alert
      put 'twitter-alerts', action: :alert_via_twitter
    end
    resources :blog_posts
    resources :authors
    resources :post_sections, path: 'sections'
    resources :events
    resources :central_banks, path: 'central-banks'
    resources :links
    resources :countries
    resources :pages, only: [:index, :edit, :update]
    resources :charts

    resources :sales_managers
    resources :users, only: [:index, :edit, :update] do
      get 'export', action: :export, on: :collection
    end
    resources :email_alerts, path: 'manual-email-alerts', only: [:new, :index, :show, :destroy] do
      get 'common-settings', action: 'common_settings'
      put 'common-settings', action: 'update_common_settings'

      get 'custom-texts', action: 'custom_texts'
      put 'custom-texts', action: 'update_custom_texts'
    end

    resources :email_alert_schedules, path: 'email-alerts-schedule', only: [:index, :new, :show, :create, :update, :destroy, :edit]
    resources :pdf_email_alerts, path: 'pdf-alerts', only: [:index, :new, :create] do
      member do
        get :preview
        put 'send', action: 'send_pdf'
      end
    end


    resources :site_settings, path: 'settings', only: [:index, :update]
  end

  resources :blog_posts, only: [:index, :show], path: 'blog'
  resources :posts, only: [:index, :show] do
    collection do
      get 'section/:section_slug', action: :index, as: :section
      get 'country/:country_slug', action: :index, as: :country
    end

    post 'mark-read', action: :mark_read, on: :member
  end

  resources :events, only: :index
  resources :links, only: :index

  resources :central_banks, only: :index, path: 'central-banks'
  resources :authors, only: [:show]
  resources :subscribers, only: [:create]
  resource  :user, only: [:create, :edit, :update] do
    collection do
      post :short_create
      post :invite_request
    end
  end

  get 'search' => 'search#index', as: :search

  get ':slug' => 'pages#show', as: :page

  root to: 'posts#index', is_home_page: true
end

app/models/email_alert_schedule.rb
class EmailAlertSchedule < ActiveRecord::Base
  serialize :user_groups, Array
  serialize :days_of_week, Array

  INTERVAL = 120

  attr_accessor :form_send_at

  has_many :automatic_email_alerts, dependent: :destroy

  before_validation :convert_form_data
  validates_presence_of :form_send_at, :greeting_message, :user_groups, :days_of_week

  validates_length_of :greeting_message, maximum: 10_000

  def self.all_days_of_week
    [ ['Sunday', 0],
      ['Monday', 1],
      ['Tuesday', 2],
      ['Wednesday', 3],
      ['Thursday', 4],
      ['Friday', 5],
      ['Saturday', 6] ]
  end

  def self.human_day_of_week(number)
    self.all_days_of_week.select {|schedule| schedule[-1] == number.to_i}.first[0]
  end

  def days_of_week=(value)
    super(value.reject(&:empty?))
  end

  def self.current
    self.all.each do |schedule|
      s = IceCube::Schedule.new(schedule.send_at, duration: INTERVAL)
      schedule.days_of_week.each do |day_of_week|
        s.add_recurrence_rule IceCube::Rule.weekly.day(day_of_week.to_i)
      end

      if s.occurring_at? Time.zone.now
        return schedule
      end
    end

    return false
  end

  def user_groups=(value)
    super(value.reject(&:empty?))
  end

  def name
    #self.class.all_days_of_week[days_of_week][0]}
    "At #{I18n.l(send_at, format: :time)}"
  end

  def convert_form_data
    if self.form_send_at
      self.send_at = Time.zone.parse(self.form_send_at)
    end
  end

  def prepare_form_data
    self.form_send_at = self.send_at.try(:strftime, '%I:%M %p')
  end
end

app/controllers/admin/email_alert_schedules_controller.rb
class Admin::EmailAlertSchedulesController < AdminController
  before_action :find_email_alert_schedule, only: [:edit, :show, :update, :destroy]

  def index
    @schedules = EmailAlertSchedule.paginate(paginate_params)
    render 'index'
  end

  def new
    @schedule = EmailAlertSchedule.new
  end

  def create
    @schedule = EmailAlertSchedule.new(schedule_params)
    if @schedule.save
      flash[:success] = 'Automatic Email alert schedule rule was successfully created'

      redirect_to admin_email_alert_schedules_path
    else
      flash[:error] = "Can't create a Automatic Email alert schedule rule. Checkout the errors below"
      @schedule.prepare_form_data
      render 'new'
    end
  end

  def edit
    @schedule.prepare_form_data
  end

  def show
    @automatic_alerts = @schedule.automatic_email_alerts.includes(:posts)
                          .where('created_at >= :date', date: Date.today.at_beginning_of_month).order('created_at desc')
  end

  def update
    @schedule.attributes = schedule_params
    if @schedule.save
      flash[:success] = 'Automatic Email alert schedule rule was successfully updated'

      redirect_to admin_email_alert_schedules_path
    else
      flash[:error] = 'Please check out the update errors below'
      render 'edit'
    end
  end

  def destroy
    if  @schedule.destroy
      flash[:success] = 'Automatic Email alert schedule rule was successfully destroyed'
    else
      flash[:error] = 'Can\'t destroy Email alert schedule rule '
    end

    redirect_to admin_email_alert_schedules_path
  end

  protected

  def find_email_alert_schedule
    @schedule = EmailAlertSchedule.find(params[:id])
  end

  def schedule_params
    params.require(:email_alert_schedule).permit(:send_at, :greeting_message, :form_send_at, user_groups: [], days_of_week: [])
  end
end

app/views/admin/email_alert_schedules/_form.html.slim
= simple_form_for [:admin, @schedule], html: { class: 'form form-horizontal' }, wrapper: :horizontal_form do |f|
  .form-body
    = f.input :form_send_at, as: :string, input_html: { class: 'timepicker-input' }
    = f.input :user_groups, collection: EmailAlert.user_groups.collect{|key, val| [key.humanize, val]}, input_html: { multiple: 'multiple', 'data-custom-select' => true, class: 'select2me' }
    = f.input :days_of_week, as: :select, collection: EmailAlertSchedule.all_days_of_week, input_html: { multiple: 'multiple', 'data-custom-select' => true, class: 'select2me' }
    = f.input :greeting_message, input_html: { rows: 6, value: @schedule.greeting_message || SiteSetting.find_by(code: 'greeting_message').try(:value) }

  = form_buttons f, cancel_path: admin_email_alert_schedules_path

app/views/admin/email_alert_schedules/_header_and_breadcrumbs.html.slim
.row
  .col-md-12
    h3.page-title
      i.fa.header-icon.fa-paper-plane-o>
      ' Automatic Email Alerts Schedule
      small management

    ul.page-breadcrumb.breadcrumb
      li.btn-group
        = link_to new_admin_email_alert_schedule_path, class: 'btn btn-primary blue' do
          i class="fa fa-plus"
          span Add alert schedule rule
      li
        i class="fa fa-home"
        '
        = link_to 'Dashboard', admin_path
      - breadcrumbs.each do |name, path|
        li
          '
          i class="fa fa-angle-right"
          '
          = link_to raw(name), path
.row
  .col-md-12
    = render 'flash_messages'

app/views/admin/email_alert_schedules/edit.html.slim
= render 'header_and_breadcrumbs',
  breadcrumbs: { 'Automatic Email Alerts schedule' => admin_email_alert_schedules_path,
                 "Editing <small>'#{@schedule.name}'</small>" => edit_admin_email_alert_schedule_path(@schedule) }
h1.page-title= "Editing  ' #{@schedule.name} '"
= render 'form'

app/views/admin/email_alert_schedules/index.html.slim
= render 'header_and_breadcrumbs', breadcrumbs: {'Automatic Email Alerts schedule' => admin_email_alert_schedules_path }
- if @schedules.any?
  table.table.table-striped.table-hover.table-events
    thead
      tr
        th Day of week
        th Send at
        th User groups
        th.expanded-actions Actions
    tbody
      - @schedules.each do |schedule|
        - edit_path = edit_admin_email_alert_schedule_path(schedule)
        tr.gradeX
          td
            ' Every
            = schedule.days_of_week.map {|day| EmailAlertSchedule.human_day_of_week(day) }.join(', ')
          td = link_to l(schedule.send_at, format: :time), edit_path
          td = schedule.user_groups.map(&:humanize).join(', ')

          td.actions
            = link_to admin_email_alert_schedule_path(schedule), class: 'btn default btn-xs blue'
              i.fa.fa-eye>
              | Show

            '
            = link_to edit_path, class: 'btn default btn-xs purple'
              i.fa.fa-edit>
              | Edit

            '
            = link_to admin_email_alert_schedule_path(schedule), class: 'btn default btn-xs', method: :delete, data: {confirm: 'Are you sure?'} do
              i.fa.fa-trash-o>
              | Delete

  .pagination-container.clearfix
    = paginate_list @schedules
    = paginate_per
- else
  .no-items
    p There are no Automatic Email Alerts

app/views/admin/email_alert_schedules/new.html.slim
= render 'header_and_breadcrumbs',
  breadcrumbs: { 'Automatic Email Alerts Schedule' => admin_email_alert_schedules_path,
                 'Creating new Alert schudule rule' => new_admin_email_alert_schedule_path }

h1.page-title New Automatic Email Alert
= render 'form'

app/views/admin/email_alert_schedules/show.html.slim
= render 'header_and_breadcrumbs',
  breadcrumbs: { 'Automatic email alerts schedule' => admin_email_alert_schedules_path,
                 "Statistics for <small>'##{@schedule.id}' at #{@schedule.name}</small>" => admin_email_alert_schedule_path(@schedule) }

h3.section-name Common info
.row
  .col-md-2 Greeting message:
  .col-md-10
    = @schedule.greeting_message
.row
  .col-md-2 User groups:
  .col-md-10
    = @schedule.user_groups.map(&:humanize).join(', ')

h3.section-name Statistics for #{Date.today.strftime("%B %Y")}
- @automatic_alerts.each do |alert|
  h4 = l(alert.created_at, format: :long)
  table.table.table-striped.table-hover.table-posts
    thead
      tr
        th Date
        th Post
    tbody
      - alert.posts.each do |post|
        tr.odd.gradeX
          td = l(post.published_at, format: :long)
          td= link_to post.headline, edit_admin_post_path(post)