config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, path: 'cms-auth', path_names: { sign_in: 'signin', sign_out: 'signout' }

  devise_for :users,
             path_names: { sign_in: 'signin', sign_up: 'singup', sign_out: 'signout' },
             controllers: { cas_sessions: 'cas_sessions' }
  get 'auth/twitter', as: :twitter_auth
  get 'auth/twitter/callback', to: 'twitter#create'
  delete 'auth/twitter/:id', to: 'twitter#destroy', as: :remove_twitter

  get 'sitemap' => 'site#sitemap', format: :xml

  get 'admin', to: redirect('/admin/dashboard')
  namespace :admin do
    get 'dashboard' => 'dashboard#index'

    get 'digest' => 'dashboard#digest', as: :digest

    resources :posts do
      get 'twitter-alerts', action: :new_twitter_alert
      put 'twitter-alerts', action: :alert_via_twitter
    end
    resources :blog_posts
    resources :authors
    resources :post_sections, path: 'sections'
    resources :events
    resources :central_banks, path: 'central-banks'
    resources :links
    resources :countries
    resources :pages, only: [:index, :edit, :update]
    resources :charts

    resources :sales_managers
    resources :users, only: [:index, :edit, :update] do
      get 'export', action: :export, on: :collection
    end
    resources :email_alerts, path: 'manual-email-alerts', only: [:new, :index, :show, :destroy] do
      get 'common-settings', action: 'common_settings'
      put 'common-settings', action: 'update_common_settings'

      get 'custom-texts', action: 'custom_texts'
      put 'custom-texts', action: 'update_custom_texts'
    end

    resources :email_alert_schedules, path: 'email-alerts-schedule', only: [:index, :new, :show, :create, :update, :destroy, :edit]
    resources :pdf_email_alerts, path: 'pdf-alerts', only: [:index, :new, :create] do
      member do
        get :preview
        put 'send', action: 'send_pdf'
      end
    end


    resources :site_settings, path: 'settings', only: [:index, :update]
  end

  resources :blog_posts, only: [:index, :show], path: 'blog'
  resources :posts, only: [:index, :show] do
    collection do
      get 'section/:section_slug', action: :index, as: :section
      get 'country/:country_slug', action: :index, as: :country
    end

    post 'mark-read', action: :mark_read, on: :member
  end

  resources :events, only: :index
  resources :links, only: :index

  resources :central_banks, only: :index, path: 'central-banks'
  resources :authors, only: [:show]
  resources :subscribers, only: [:create]
  resource  :user, only: [:create, :edit, :update] do
    collection do
      post :short_create
      post :invite_request
    end
  end

  get 'search' => 'search#index', as: :search

  get ':slug' => 'pages#show', as: :page

  root to: 'posts#index', is_home_page: true
end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  include Concerns::Sluggable
  self.per_page = 20

  has_and_belongs_to_many :countries

  validate :one_country_at_least

  scope :latest, -> { where(published: true).order('published_at DESC') }

  mount_uploader :cover, PostCoverUploader

  def countries_names
    countries.map(&:name).join(', ')
  end

  protected

  def slug_source
    [headline, rand(10_000) + 100]
  end

  def one_country_at_least
    if countries.size == 0
      errors.add(:countries, 'You need to add at least one country')
    end
  end
end

app/controllers/admin/blog_posts_controller.rb
class Admin::BlogPostsController < AdminController
  before_action :find_blog_post, only: [:edit, :update, :show, :destroy]

  def index
    posts = BlogPost

    @q = posts.search(params[:q])
    @blog_posts = @q.result.paginate(paginate_params)
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)

    if @blog_post.save
      process_blog_post_on_success_update(@blog_post)
    else
      flash[:error] = "Can't create a blog post. Checkout the errors below"
      render 'new'
    end
  end

  def edit
  end

  def update
    if @blog_post.update(blog_post_params)

      process_blog_post_on_success_update(@blog_post)
    else
      flash[:error] = 'Please checkout the blog post updating errors'
      render 'edit'
    end
  end

  def destroy
    @blog_post.destroy if @blog_post.present?

    redirect_to admin_blog_posts_path, flash: { success: 'Blog Post was successfully removed.' }
  end

  private

  def process_blog_post_on_success_update(blog_post)
    redirect_path = admin_blog_posts_path
    case params[:commit]
    when 'Save'
      flash[:success] = 'Blog post was successfully updated'
    when 'Preview'
      session[:blog_post_preview_id] = blog_post.id
      redirect_path = blog_post_path(blog_post.id)
    when 'Publish'
      blog_post.published = true
      blog_post.published_at ||= Time.zone.now
      blog_post.save

      flash[:success] = 'Blog post was successfully published'
    end

    redirect_to redirect_path
  end

  def find_blog_post
    @blog_post = BlogPost.friendly.find(params[:id])
  end

  def blog_post_params
    params.require(:blog_post).permit(
      :cover, :remove_cover, :cover_remove, :headline, :content,
      :readout, :published_at, :published, country_ids: [])
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < FrontController
  PER_PAGE = 5

  def index
    @blog_posts = BlogPost.latest.paginate(page: params[:page], per_page: PER_PAGE)
    @next_page_path = blog_posts_path page: @blog_posts.next_page

    respond_to do |format|
      format.html
      format.js
      format.rss
    end
  end

  def show
    @blog_post = BlogPost.friendly.find(params[:id])
  end
end

app/views/admin/blog_posts/_filter_form.html.slim
.filter-form.row
  = search_form_for @q, url: admin_blog_posts_path do |f|
    .col-md-10
      = f.search_field :headline_or_content_cont, class: 'form-control input-lg', placeholder: 'Search by headline, content'

    .col-md-2
      = f.submit 'Search', class: 'btn btn-lg btn-success submit-button'

app/views/admin/blog_posts/_form.html.slim
= simple_form_for [:admin, @blog_post], html: { class: 'form form-horizontal' }, wrapper: :horizontal_form do |f|
  .form-body
    = f.input :published, as: :boolean, label: 'Published?'
    = f.input :published_at, as: :string, label: 'Publication date & time', input_html: { value: (l(@blog_post.published_at || Time.zone.now, format: :post_edit)), class: 'datepicker', 'data-datetime-picker' => true }

    h2.form-section Content
    = f.input :headline
    = f.input :readout
    = f.input :content, as: :ckeditor, input_html: {rows: 32}

    h2.form-section Cover
    = f.input :cover, as: :image, input_html: {version: :thumb}
    - unless @blog_post.cover.blank?
      = f.input :remove_cover, as: :boolean

    = f.association :countries, input_html: { class: 'select2me' }, required: true

  .form-actions.fluid
    .col-md-offset-2.col-md-10
      = f.button :submit, 'Save', class: 'green'
      = f.button :submit, 'Preview', class: 'btn-primary'
      = f.button :submit, 'Publish', class: 'purple'
      = link_to 'Cancel', admin_blog_posts_path, class: 'btn btn-lg default'

app/views/admin/blog_posts/_header_and_breadcrumbs.html.slim
.row
  .col-md-12
    h3.page-title
      i.fa.fa-header.fa-files-o
      '
      ' Blog Posts
      small management

    ul.page-breadcrumb.breadcrumb
      li.btn-group
        = link_to new_admin_blog_post_path, class: 'btn btn-primary blue' do
          i class="fa fa-plus"
          span Add new blog post
      li
        i class="fa fa-home"
        '
        = link_to 'Dashboard', admin_path
      - breadcrumbs.each do |name, path|
        li
          '
          i class="fa fa-angle-right"
          '
          = link_to raw(name), path
.row
  .col-md-12
    = render 'flash_messages'

app/views/admin/blog_posts/edit.html.slim
= render 'header_and_breadcrumbs',
  breadcrumbs: { 'Blog Posts' => admin_blog_posts_path,
                 "Editing <small>'#{truncate(@blog_post.headline, length: 36)}'</small>" => edit_polymorphic_path([:admin, @blog_post]) }
h1.page-title= "Editing   ' #{@blog_post.headline} '"
= render 'form'

app/views/admin/blog_posts/index.html.slim
= render 'header_and_breadcrumbs', breadcrumbs: {'Blog Posts' => admin_blog_posts_path }

= render 'filter_form'
- if @blog_posts.any?
  table.table.table-striped.table-hover.table-posts
    thead
      tr
        th.preview Cover
        th.w-140 = sort_link(@q, :published_at)
        th.w-240 Headline
        th.actions Actions
    tbody
      - @blog_posts.each do |post|
        - edit_path = edit_admin_blog_post_path(post.id)
        tr.gradeX
          td.preview
            - if post.cover.path
              = image_tag post.cover.thumb.url if post.cover.path
            - else
              = image_tag 'admin/post-cover-placeholder.png'
          td
            -if post.published_at
              = l(post.published_at, format: :post_list)
          td = link_to truncate(post.headline, length: 80), edit_path
          td.actions
            = link_to edit_path, class: 'btn default btn-xs purple'
              i.fa.fa-edit>
              | Edit

            '
            = link_to admin_blog_post_path(post.id), class: 'btn default btn-xs', method: :delete, data: {confirm: 'Are you sure?'} do
              i.fa.fa-trash-o>
              | Delete

  .pagination-container.clearfix
    = paginate_list @blog_posts
    = paginate_per
- else
  .no-items
    p There are no blog posts

app/views/admin/blog_posts/new.html.slim
= render 'header_and_breadcrumbs',
  breadcrumbs: { 'Blog Posts' => admin_blog_posts_path,
                 'Creating new blog post' => new_admin_blog_post_path }

h1.page-title New post
= render 'form'